version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing Maven dependencies and building the JAR file...
      - mvn clean install -DskipTests # Compile le projet et génère le fichier JAR
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t javaservice . # Construit l'image Docker
      - docker tag javaservice:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/javaservice:latest
  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/javaservice:latest # Pousse l'image dans ECR
      - echo Writing image details to imagedefinitions.json...
      - printf '[{"name":"javaservice","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/javaservice:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
