services:
  java-service:
    image: java-service
    container_name: java-service-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8081:8081"
    restart: unless-stopped